services:
  discord_docker_bot:
    container_name: discord_docker_bot
    image: manucarcor/discord_docker_bot:latest
    environment:
      - DISCORD_TOKEN=foo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock